/**
 * Build Tailwind → src/tw-inline.js (string export for Workers bundle).
 */
import { execFileSync } from "node:child_process"
import { writeFileSync, mkdirSync, readFileSync } from "node:fs"
import { dirname, join } from "node:path"
import { fileURLToPath } from "node:url"

const root = join(dirname(fileURLToPath(import.meta.url)), "..")
const input = join(root, "src/styles.css")
const outCss = join(root, "dist/styles.css")
mkdirSync(join(root, "dist"), { recursive: true })

const bin = join(root, "node_modules/.bin/tailwindcss")
try {
  execFileSync(bin, ["-i", input, "-o", outCss, "--minify"], {
    cwd: root,
    stdio: "inherit",
  })
} catch {
  execFileSync(
    "pnpm",
    ["exec", "tailwindcss", "-i", input, "-o", outCss, "--minify"],
    { cwd: root, stdio: "inherit" },
  )
}

const css = readFileSync(outCss, "utf8")
writeFileSync(
  join(root, "src/tw-inline.js"),
  `/** Auto-generated by scripts/build-css.mjs — do not edit */\nexport default ${JSON.stringify(css)}\n`,
)
console.log("[cloudflare] wrote src/tw-inline.js")
